import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import React from 'react'
import Banner from "../components/banner";
import About from "../components/about";
import Portfolio from "../components/portfolio";
import Testimonial from "../components/testimonial";
import initFirebase from '../components/firebase/initFirebase';
import WriteFirebase from '../components/firestore/write'
import ReadFirebase from '../components/firestore/read'
import Log from "../components/log";

initFirebase();
WriteFirebase();
ReadFirebase();

 const Home:React.FC = () => { 

  return (
    <div>
      <Head>
        <title>Portfolio Of Duc Dinh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
            <Banner />
            <About />
            <Portfolio />
            <Testimonial/>
            <Log/>
        </Layout>
    </div>
  )
}
export default Home