import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import React from 'react'
import Banner from "../components/banner";
import About from "../components/about";
import Portfolio from "../components/portfolio";
import Testimonial from "../components/testimonial";
import initFirebase from '../components/firebase/initFirebase';
import WriteFirebase from '../components/firestore/write'
import ReadFirebase from '../components/firestore/read'
import Log from "../components/log"
import { getUserFromCookie } from '../components/auth/userCookies'
var userData = getUserFromCookie();
console.log(userData);

initFirebase();

const Home: React.FC = () => {
  var a = 0;
  return (
    <div>
      <Head>
        {userData && userData.short_name ? (
          <title>Portfolio Of {userData.short_name}</title>
        ) : (
          <title>Portfolio Of Someone</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {userData && userData.short_name ? (
            <Banner shortName={userData.short_name} profession={userData.profession}/>

        ) : (
            <Banner />
        )
      }
      <About />
        <Portfolio />
        <Testimonial />
        <Log />
      </Layout>
    </div>
  )
}
export default Home