import Head from 'next/head'
import Layout from '../components/layout'
import React, { useMemo } from 'react'
import Banner from "../components/banner";
import About from "../components/about";
import Portfolio from "../components/portfolio";
import Testimonial from "../components/testimonial";
import Log from "../components/log"
import { useUserContext } from '../context/userContext'
import { getUserFromCookie } from '../components/auth/userCookies'
import { useEffect } from 'react';

const Home: React.FC = () => {
  const { userSession } = useUserContext();
  
  return (
    <div>
      <Head>
        {userSession && userSession.short_name ? (
          <title>Portfolio Of {userSession.short_name}</title>
        ) : (
          <title>Portfolio Of Someone</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {userSession && userSession.short_name ? (
          <>
            <Banner short_name={userSession.short_name} profession={userSession.profession} />
            <About full_name={userSession.full_name} profession={userSession.profession} avatar_url={userSession.avatar_url} />
            <Log doc_id={userSession.docId} />
          </>
        ) : (
          <>
            <Banner />
            <About />
            <Log />
          </>
        )
        }
        <Portfolio />
        <Testimonial />
      </Layout>
    </div>
  )
}
export default Home